app:
  csv_path: ../output/orders.csv

logger:
  level: INFO
  file_path: ../logs/logs_{time}.log

generators:
  max_orders: 2000
  # percentage of orders in InProcess, Fill/PartialFill/Cancel, Done statuses
  percent_completed_orders: 30
  # percentage of orders in New, InProcess, Fill/PartialFill/Cancel, Done statuses
  percent_created_and_completed_orders: 60
  # percentage of orders in New, InProcess, Fill/PartialFill/Cancel statuses
  percent_created_orders: 10
  id_generator:
    seed: 1
    start: 1
    stop: 9999999999999
  px_fill_generator:
    rounding: 5
    start: 0.1
    stop: 1.0
  volume_init_generator:
    rounding: -2
    start: 100
    stop: 15000
  date_generator:
    start: 100
    stop: 15000
    start_date: 2022-01-01T00:00:00.000000Z