ORDER_ID_MIN_LENGTH = 1
ORDER_ID_MAX_LENGTH = 9999999999999

ORDER_PX_ROUNDING = 5
ORDER_PX_FILL_START = 0.1
ORDER_PX_FILL_STOP = 1.0

ORDER_VOLUME_INIT_START = 100
ORDER_VOLUME_INIT_STOP = 15000
ORDER_VOLUME_ROUNDING = -2

ORDER_DATE_INCREMENT_START = 100
ORDER_DATE_INCREMENT_STOP = 15000

MAX_NUMBER_ORDERS = 2000

# percentage of orders created before recording started
ORDERS_CREATED_BEFORE_RECORDING = 30

# percentage of orders that were created when the recording started
ORDERS_CREATED_AND_DONE = 60

# percentage of orders completed after the end of the recording
ORDERS_COMPLETED_AFTER_RECORDING = 10

# the number of orders to generate in each segment
MAX_LIMIT_ORDERS_FOR_FIRST_SEGMENT = int((MAX_NUMBER_ORDERS / 100) * ORDERS_CREATED_BEFORE_RECORDING)

MAX_LIMIT_ORDERS_FOR_SECOND_SEGMENT = int(
    (MAX_NUMBER_ORDERS / 100) * ORDERS_CREATED_AND_DONE + MAX_LIMIT_ORDERS_FOR_FIRST_SEGMENT)

# the number of records to generate in each segment
NUMBER_OF_RECORDS_FOR_FIRST_SEGMENT = 3

NUMBER_OF_RECORDS_FOR_SECOND_SEGMENT = 4

NUMBER_OF_RECORDS_FOR_THIRD_SEGMENT = 3

# the number of records to generate in each segment
MAX_LIMIT_RECORDS_FOR_FIRST_SEGMENT = int(
    (MAX_NUMBER_ORDERS / 100) * ORDERS_CREATED_BEFORE_RECORDING) * NUMBER_OF_RECORDS_FOR_FIRST_SEGMENT

MAX_LIMIT_RECORDS_FOR_SECOND_SEGMENT = int((
                                                       MAX_NUMBER_ORDERS / 100) * ORDERS_CREATED_AND_DONE) * NUMBER_OF_RECORDS_FOR_SECOND_SEGMENT + MAX_LIMIT_RECORDS_FOR_FIRST_SEGMENT
